### ISSUE TITLE
GPU support

### ISSUE THREAD

**Issue by ofirkris** [IBM/MAX-Fast-Neural-Style-Transfer#34]
Is there a way to config current code to run through GPU?

**Comment by MLnick** [comment]
Currently it is not supported. You would have to modify the `Dockerfile` to build off the correct CUDA base image (see https://hub.docker.com/r/nvidia/cuda/), and update any Pytorch dependencies to support GPU. You could then re-build the image.

**Comment by ofirkris** [comment]
Thanks.
